/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MathProblem {
        "range": number;
    }
}
declare global {
    interface HTMLMathProblemElement extends Components.MathProblem, HTMLStencilElement {
    }
    var HTMLMathProblemElement: {
        prototype: HTMLMathProblemElement;
        new (): HTMLMathProblemElement;
    };
    interface HTMLElementTagNameMap {
        "math-problem": HTMLMathProblemElement;
    }
}
declare namespace LocalJSX {
    interface MathProblem {
        "range"?: number;
    }
    interface IntrinsicElements {
        "math-problem": MathProblem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "math-problem": LocalJSX.MathProblem & JSXBase.HTMLAttributes<HTMLMathProblemElement>;
        }
    }
}
